
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
  sh "flutter clean"
  sh "flutter build apk --release --target lib/main.dart --no-tree-shake-icons "
    firebase_app_distribution(
    app: "1:412322100407:android:5eb44772341ba2b2798932",
    firebase_cli_token: "1//09yGRmiflI_BnCgYIARAAGAkSNwF-L9IrDf_1JIfTevLzE8mb16V9IUIM946S0BpeXWo9Zb-QXhNeH_mg5vqM8lcuILYNMlxYO0k",
    upload_timeout: 600,
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
    testers: "mohamedhisham67751@gmail.com,elgammal2024@gmail.com,islamabdelkarim7@gmail.com,mahmo4udi@gmail.com",
    release_notes: "This is a test release for the app."
    
    
  )
  end


end
